[package]
name = "cfr"
version = "0.1.0"
edition = "2021"


[dependencies]
ebnf = { git = "https://github.com/fwander/ebnf_with_names"}
tera = "1"
once_cell = "1.16.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
